### PR TITLE
Added the column Comment to the AgentITSMService screen

### PR DESCRIPTION
**Pull request by Rooobaaat**
Added the column Comment to the AgentITSMService screen to give agents more information about a service

### CODE REVIEW

**Comment by nilei** [comment]
👍

**Comment by UdoBretz** [comment]
Hi Robert,

thanks, nice! But please add the comment also to the AgentITSMServiceZoom screen, so that the information in the overview and in the zoom are consistent. The same also for AgentSLA overview and zoom please.

Best regards,
Udo

**Comment by Rooobaaat** [comment]
Hi Udo,

thank you for your feedback! I'll update my PR today in the evening :)

**Comment by UdoBretz** [comment]
Thanks Robert! Merged!

**Pull request closed without merging**
