### PR TITLE
Master port to OM - ITSMCore/Service_SLA

### PR DESCRIPTION
**Pull request by s7design**
Hello @UdoBretz ,

Here's PR for the first part of ITSMCore, Service port to OM with selenium tests. Remaining ITSMCore/SLA will follow up soon.
Since $LayoutObject->{LanguageObject}->Get() will no longer be used due to function depreciation, it is changed to $LayoutObject->{LanguageObject}->Translate(). It is included in this PR, but if you would prefer to be it in a separate one, I will update PR accordingly.

Regards,
Sanjin

### CODE REVIEW

**Comment by s7design** [comment]
Hello @UdoBretz ,

ITSMCore port is concluded with latest commits. There is one question if you could clarify please. 
In LinkObjectService.pm, new layout object is created. I left it in constructor but used OM in it's creation. Now main issue is that i couldn't test it out, since mine knowledge in this field is limited. If you could just explain how could we test it, to link 2 different services, it would be great. It will help for future porting and understanding of ITSM modules as well. If there is a mistake on this part i will update PR asap.

Regards,
Sanjin

**Comment by s7design** [comment]
Hi @UdoBretz,

While we did porting to OM, we saw that there are bug in Kernel/Modules/AgentITSMSLAPrint.pm and Kernel/Modules/AgentITSMServicePrint.pm.
I felt free to solve that. I hope it is OK, I will be able to open new PR only for this issue,  if you want.  
Please, let me know, what you think about that.

Regards
Zoran

**Comment by UdoBretz** [comment]
Merged. Thank you!

**Comment by UdoBretz** [comment]
Hi Zoran. I found 2 problems here, did you test the ITSMCore modules in the frontend?

1. The template Path should be Kernel/Output/HTML/Templates/ instead of Kernel/Output/HTML/Template/
2. The frontend module registration for AdminITSMCIPAllocate does not work. 
<NavBarModule>
                    <Module>Kernel::Output::HTML::NavBarModuleAdmin</Module>     (wrong)
                    <Module>Kernel::Output::HTML::NavBar::ModuleAdmin</Module>   (correct)
Thank you,
Udo

**Comment by s7design** [comment]
Hi @UdoBretz,

Yes we tested this in one VM, and then committed from another one, maybe there we made this mistake.

We will check this soon.
It will be done.

Regards
Zoran

**Comment by UdoBretz** [comment]
Thank you!

**Comment by s7design** [comment]
Hi @UdoBretz 

I updated this PR, I hope now it works.
I tested all test from this module, all of them worked.

Regards
Zoran

**Comment by UdoBretz** [comment]
Hi Zoran,

thanks, works fine!

Best regards,
Udo

**Pull request closed without merging**
